<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
    <NoWarn>$(NoWarn);WFO5001</NoWarn>
  </PropertyGroup>
</Project>